### ISSUE TITLE
Urls are encoded within prefilled Table

### ISSUE THREAD

**Issue by iliraga** [fiduswriter/simple-datatables#244] opened 2023-01-24 10:16 UTC
Hi there

I have a table which is generated in PHP code and looks roughly like this:

```
            <table class="table is-fullwidth is-striped is-interactive-datatable">
                <thead>
                    <tr>
                        <th>Project</th>
                        <th>ID</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($projects as $project): ?>
                    <?php $projectUrl = $gomar->url('task-board', ['project' => $project->key]); ?>
                    <tr>
                      <td><a href="<?= $projectUrl ?>"><?= $project->name; ?></a></td>
                      <td><span class="tag is-success is-light"><?= $project->key; ?></a></td>
                      <td class="is-size-7"><?= $project->description; ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
```

The interesting line is this one:

`<td><a href="<?= $projectUrl ?>"><?= $project->name; ?></a></td>`

This one basically just renders an URL which itself is in the correct format and contains one queryparameter.

After rendering it, it looks like this:

```<a href="/bootstrap/execute.php?controller=task-board&amp;amp;project=ACCH">Cycling &amp; Challenges</a>```

So basically after initialising the datatable it replaces all URLs with html encoded varaints. When disabling the datatable (by removing that `is-interactive-datatable`-class it works.

This sounds like it's not a bug but rather intended behaviour. The problem is: It used to work always.

In the version `5.0.3` it works. Afterwards it started to introduce that behaviour.

```
const dataTable = new simpleDatatables.DataTable(".is-interactive-datatable", {
            perPage: 25
        }); 
```

Is there an additional option when initialising a datatable which needs to be passed to the constructor?

**Comment by johanneswilm** [comment] 2023-01-24 10:19
Hey @iliraga,
isn't that a PHP issue? simpleDataTables is JavaScript only. So whatever the PHP renders for it on the server, it uses in the client (browser). 

Or did I misunderstand what you are trying to do?

**Comment by johanneswilm** [comment] 2023-01-24 10:22
Could you give me the code of what it looks like if in your browser you click on "show source" of that table? So that is the table after PHP has done its rendering of it.

**Comment by johanneswilm** [comment] 2023-01-24 13:33
@iliraga I tried it out without the information I requested from you, but just adding a link like `<a href="/bootstrap/execute.php?controller=task-board&amp;project=ACCH">Cycling &amp; Challenges</a>` did not destroy that link for me using version 6.0.8. So maybe your link looks somewhat different? (after PHP, when sent to the browser)

Please reopen if you are able to provide this information. I'm closing it now as I cannot determine whether it's actually a bug with the information I have right now.

**Closed by johanneswilm** 2023-01-24 13:33 UTC

**Comment by mdetre** [comment] 2023-01-30 09:05
Hi, 
I think i have the same problem. I will try to explain to you.
Currently I'm working on PHP 8.1.13 and laravel 9.
I'm using the latest version of simple datatables 
 `<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">`
`<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>`

I will take the example of a very simple blade present in my project : 

For example, I have a basic table with thead and some th. But I defined the first th like this : `<th>&nbsp;</th>`. The problem is that I have the "&nbsp" on display. If I inspect the code and copy/paste the line into notepad, the & has turned into `&amp;`. This therefore gives : `&amp;nbsp;`.

Another example, I have this line of code that allows me to call a route when I click the button : 
`<input class="form-check-input" type="checkbox" onclick="window.location.href='{{route('user.desactivateField', ['id' => $row->id, 'field' => 'is_enabled', 'locale' => app()->getLocale()])}}'" checked value="" />` 

When I inspect code with latest version of simple datatables (same with version 6) :
`<input class="form-check-input" type="checkbox" onclick="window.location.href='http://localhost-laravel/fr/user.desactivateField?id=1&amp;amp;field=is_enabled'" checked="" value="">` 

When I inspect code with 5th version of simple datatables :
`<input class="form-check-input" type="checkbox" onclick="window.location.href='http://localhost-laravel/fr/user.desactivateField?id=1&amp;field=is_enabled'" checked="" value="">`

As you can see, the **&** is changed to `&amp;` This behavior started with version 6 of simple datatables. If I change the used version of simple datatables to version 5 or remove it, I no longer have a problem.

**Comment by johanneswilm** [comment] 2023-01-30 09:48
@mdetre Ok, can you paste here what it says there if you select "View page source" in your browser? The problem you guys tell me what it says in PHP and then what SDT makes of it. But I need the HTML code as it arrives in the browser before SDT changes it. I have not been able to reproduce that based on the information that @iliraga provided me with.

**Comment by mdetre** [comment] 2023-01-30 10:06
Here are two screenshots of my two examples when I click "View Page Source Code" : 
![th](https://user-images.githubusercontent.com/59249568/215447482-389eec80-adb0-43a1-ad7e-ced1cfce7318.png)
![url](https://user-images.githubusercontent.com/59249568/215447485-a8ce2158-2967-47f0-ab24-bac107cc5d94.png)

**Comment by johanneswilm** [comment] 2023-01-30 10:09
@mdetre Isn't that what you see in the inspector under "Elements"? That will be the HTML after SDT has modified it. I need to see what it looks like as it comes from the server, before SDT has touched it. If you hit CTRL+U in Chrome, that should show you what that looks like.

**Comment by mdetre** [comment] 2023-01-30 10:21
I'm on chrome and the "View page source code" is indeed the shortcut CTRL U..

**Comment by johanneswilm** [comment] 2023-01-30 10:28
@mdetre OK, I'll try.

**Comment by Thomas-Molen** [comment] 2023-01-30 15:14
I'm having the same issue with ASP.Net MVC, <a asp-action> tags with mutliple asp-route- properties will have "&amp;" added between the query parameters in the href url

**Comment by johanneswilm** [comment] 2023-01-30 21:47
Hey, this should now be fixed. Please try version 7.0.2.

**Comment by mdetre** [comment] 2023-01-31 12:36
It's fixed ! Thank you
